# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityReadings',
            fields=[
                ('ReadingID', models.AutoField(primary_key=True, serialize=False)),
                ('DateAndTime', models.DateTimeField(verbose_name='date published')),
                ('Reading', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PointLocations',
            fields=[
                ('LocationID', models.AutoField(primary_key=True, serialize=False)),
                ('PlaceName', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=500)),
                ('Latitude', models.CharField(max_length=50)),
                ('Longitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='airqualityreadings',
            name='LocationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airqsapp.PointLocations'),
        ),
    ]
