# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airqsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airqualityreadings',
            old_name='LocationID',
            new_name='LocationOfReading',
        ),
    ]
